import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const url = (p) => fileURLToPath(new URL(p, import.meta.url));

export function extractDsHex(tokensCss) {
  const out = {};
  const re = /(--ds-[a-z0-9-]+)\s*:\s*(#[0-9a-fA-F]{3,8})\s*;/g;
  let m;
  while ((m = re.exec(tokensCss))) out[m[1]] = m[2].toLowerCase();
  return out;
}

export function hexToHslTriplet(hex) {
  let h = hex.replace("#", "");
  if (h.length === 3) h = h.split("").map((c) => c + c).join("");
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let hue = 0, sat = 0;
  const lig = (max + min) / 2;
  const d = max - min;
  if (d !== 0) {
    sat = lig > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) hue = (g - b) / d + (g < b ? 6 : 0);
    else if (max === g) hue = (b - r) / d + 2;
    else hue = (r - g) / d + 4;
    hue /= 6;
  }
  const H = Math.round(hue * 360);
  const S = Math.round(sat * 100);
  const L = Math.round(lig * 100);
  return `${H} ${S}% ${L}%`;
}

// shadcn var -> source --ds-* token
export const MAP = {
  "--background": "--ds-bg",
  "--foreground": "--ds-text",
  "--card": "--ds-bg",
  "--card-foreground": "--ds-text",
  "--popover": "--ds-bg",
  "--popover-foreground": "--ds-text",
  "--primary": "--ds-primary",
  "--primary-foreground": "--ds-on-primary",
  "--secondary": "--ds-surface",
  "--secondary-foreground": "--ds-text",
  "--muted": "--ds-surface-sunken",
  "--muted-foreground": "--ds-text-muted",
  "--accent": "--ds-surface",
  "--accent-foreground": "--ds-text",
  "--destructive": "--ds-error",
  "--destructive-foreground": "--ds-on-primary",
  "--border": "--ds-border",
  "--input": "--ds-border",
  "--ring": "--ds-primary",
  "--chart-1": "--ds-primary",
  "--chart-2": "--ds-accent-ochre",
  "--chart-3": "--ds-accent-teal",
  "--chart-4": "--ds-success",
  "--chart-5": "--ds-error"
};

function buildShadcnBlock(dsHex) {
  const lines = Object.entries(MAP).map(([v, ds]) => {
    if (!dsHex[ds]) throw new Error(`tokens.css missing ${ds} for ${v}`);
    return `  ${v}: ${hexToHslTriplet(dsHex[ds])};`;
  });
  return `:root {\n${lines.join("\n")}\n  --radius: 1rem;\n}\n`;
}

function main() {
  const tokens = readFileSync(url("../src/tokens.css"), "utf8");
  const head = readFileSync(url("../src/tailwind.head.css"), "utf8");
  const dsHex = extractDsHex(tokens);
  const banner =
    "/* GENERATED by scripts/generate-bridge.mjs from src/tokens.css.\n" +
    "   Do not edit by hand. Run `npm run generate`. */\n";
  const shadcn =
    "/* shadcn HSL bridge — derived from --ds-* tokens */\n" +
    buildShadcnBlock(dsHex);
  writeFileSync(url("../src/tailwind.css"), banner + head + "\n" + shadcn);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
